### ISSUE TITLE
关于您的代码中是实验2和实验3中预测准确率的问题

### ISSUE THREAD

**Issue by taichanghong** [cloudworkflow/workflow-performance-prediction-jii#1]
作者您好，在运行您的相关代码和阅读论文时，我有一个疑问期待获得您的解答：您的代码中run_exp2及run_exp2运行后输出的准确率是CPU准确率还是内存准确率？您在论文中提及的在实验2中,我们测试我们的模型的收敛速度。在实验3中,测试我们的整体性能测试模型。这里的整体性能指代什么呢？

**Comment by cloudworkflow** [comment]
之前综合考虑了cpu或内存的各类统计指标，通过聚类，进行了标签化，所以是一种离散的负载级别，看起来要比回归任务更直观一些。因为cpu变化比较大，更有预测意义，而内存相对变动不大，所以没有特殊说明就是指更难预测的指标，即cpu。




整体性能指的就是准确率，以及不同长度工作流下的综合表现，来跟推理速度，显存占用这些相区分(实验2)。




欢迎交流！！




高明
东北财经大学













---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月5日(周三) 下午3:04
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [cloudworkflow/workflow-performance-prediction-jii] 关于您的代码中是实验2和实验3中预测准确率的问题 (Issue #1)




 
作者您好，在运行您的相关代码和阅读论文时，我有一个疑问期待获得您的解答：您的代码中run_exp2及run_exp2运行后输出的准确率是CPU准确率还是内存准确率？您在论文中提及的在实验2中,我们测试我们的模型的收敛速度。在实验3中,测试我们的整体性能测试模型。这里的整体性能指代什么呢？

**Comment by taichanghong** [comment]
尊敬的高明教授：
您好！非常感谢您的解答，您的工作非常精彩，我对您的工作非常感兴趣，后续可能还会有一些疑问请教您，期待与您进一步的交流！祝您生活愉快，工作顺利！
邰昌鸿
河海大学

**Comment by cloudworkflow** [comment]
客气了，欢迎交流哈！
祝好运！


高明





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月5日(周三) 下午3:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cloudworkflow/workflow-performance-prediction-jii] 关于您的代码中是实验2和实验3中预测准确率的问题 (Issue #1)




 
尊敬的高明教授：
 您好！非常感谢您的解答，您的工作非常精彩，我对您的工作非常感兴趣，后续可能还会有一些疑问请教您，期待与您进一步的交流！祝您生活愉快，工作顺利！
 邰昌鸿
 河海大学

**Comment by taichanghong** [comment]
好的，谢谢您！

**Comment by taichanghong** [comment]
尊敬的高明教授：

您好！我是河海大学计算机学院的邰昌鸿。不久前，我有幸咨询了您关于准确率的问题，您的答复对我帮助很大，非常感谢。

近期，我对您在使用DAG-Transformer模型对云计算工作流性能预测的研究产生了浓厚的兴趣。您的这项工作展现了高超的研究能力，为工作流预测带来了新的研究方向和视角。在此背景下，我深感敬意，并对您和您的团队表示由衷的敬意。

在您的文章中，您提到了您和您的团队通过对阿里巴巴2018数据集的预处理，得到了4,201,013个批处理工作流。这些工作流的长度从1个任务到1,002个任务不等，其中少于10个任务的工作流占了总数的94.75%，少于20个任务的工作流则占了99.30%。我相信这些数据集对于云计算工作流预测和调度研究具有非常重要的意义。

因此，我冒昧地想请教您，是否可以分享这部分数据集，以便我们能进一步扩展至更广泛的研究领域？如果我们基于这些数据集得到了一些研究成果，我会非常感激您的帮助，并确保在后续的研究成果中充分注明您和您团队的贡献。

期待您的回复，并再次感谢您过去的指导和帮助。

此致
敬礼

邰昌鸿
河海大学计算机学院

**Comment by cloudworkflow** [comment]
您好，感谢关注！！


加我微信吧，我的手机号就行，13942693102。




高明







---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月14日(周六) 下午2:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cloudworkflow/workflow-performance-prediction-jii] 关于您的代码中是实验2和实验3中预测准确率的问题 (Issue #1)




 
尊敬的高明教授：
 
您好！我是河海大学计算机学院的邰昌鸿。不久前，我有幸咨询了您关于准确率的问题，您的答复对我帮助很大，非常感谢。
 
近期，我对您在使用DAG-Transformer模型对云计算工作流性能预测的研究产生了浓厚的兴趣。您的这项工作展现了高超的研究能力，为工作流预测带来了新的研究方向和视角。在此背景下，我深感敬意，并对您和您的团队表示由衷的敬意。
 
在您的文章中，您提到了您和您的团队通过对阿里巴巴2018数据集的预处理，得到了4,201,013个批处理工作流。这些工作流的长度从1个任务到1,002个任务不等，其中少于10个任务的工作流占了总数的94.75%，少于20个任务的工作流则占了99.30%。我相信这些数据集对于云计算工作流预测和调度研究具有非常重要的意义。
 
因此，我冒昧地想请教您，是否可以分享这部分数据集，以便我们能进一步扩展至更广泛的研究领域？如果我们基于这些数据集得到了一些研究成果，我会非常感激您的帮助，并确保在后续的研究成果中充分注明您和您团队的贡献。
 
期待您的回复，并再次感谢您过去的指导和帮助。
 
此致
 敬礼
 
邰昌鸿
 河海大学计算机学院

**Comment by taichanghong** [comment]
好的，感谢高教授！
